### PR TITLE
fix crashing when moving beyond foundations

### LINKED ISSUE #11: crash when bringing card beyond rightmost foundation

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #11

### CODE REVIEW

File: src/selectmove.cpp [hunk 1]
```diff
@@ -94,30 +83,41 @@ void SelectionOrMove::select_another_card(const Klondike& klon, SelDirection dir
...
+	{
+		int dx = (dir == SelDirection::LEFT) ? -1 : 1;
+		x += dx;
+		if (x == 2 && !is_bottom_row)   // between discard and tableau
+			x += dx;
+
+		if (0 <= x && x < 7) {
+			std::optional<CardPlace> new_place = is_bottom_row ? CardPlace::tableau(x) : card_x_to_top_place(x);
+			if (new_place && (
+					!this->ismove || is_bottom_row || new_place->kind == CardPlace::FOUNDATION))
```
Comment (Akuli) [inline src/selectmove.cpp:100]:
```suggestion
			assert(new_place);
			if (!this->ismove || is_bottom_row || new_place->kind == CardPlace::FOUNDATION)
```
